config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :tags
  end
  resources :comments do
  	collection do
  		get 'recent'
  	end
  end
  devise_for :users
  resources :users,only: [:show]
  resources :images
  resources :events
  resources :posts do
  	member do
  		get 'comments'
  	end
  end
  
  root 'posts#index'
  namespace :admin do
    #root 'dashboards#index'
    root "dashboards#posts"
    get "events/", to: "dashboards#events"
    get "images/", to: "dashboards#images"
    resources :users
    resources :categorizes
    resources :categories

  end
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/event.rb
class Event < ApplicationRecord
	
	belongs_to :user
  has_many :comments,as: :commentable
  has_many :categorizes,as: :categorizable
	has_many :categories,through: :categorizes
	accepts_nested_attributes_for :categories,allow_destroy: true

	validates :title,presence: {message: "Must exist"},length: {minimum: 3,maximum: 25}
	before_save :ensure_description_value
	validates :location,presence: true
	validates :title,uniqueness: {message: "title must be unique."}
	validates :start_time,presence: true
	validates :end_time,presence: true
	validate :check_datetime

  after_validation :set_event_slug

  def to_param
  	"#{id}-#{slug}"
  end
	private
	def ensure_description_value
		self.description = "description is not provided yet."
	end
	def check_datetime
		if self.start_time == self.end_time
			errors.add(:start_time,'cant be equal to ending time.')
		elsif self.start_time > self.end_time
			errors.add(:start_time,'cant be more that ending time.')
		end

	end
	def set_event_slug
		self.slug = self.title.to_s.parameterize
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,only: [:new,:update,:edit,:destroy]
  before_action :same_user, only: [ :edit, :update, :destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @comment = Comment.new
    @comments = @event.comments.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :location, :start_time, :end_time,:user_id,category_ids: [])
    end

    def same_user
      unless current_user.id == @event.user.id
        redirect_to events_path
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_comments.html.erb
<% comments.each do |comment| %>
  <% if comment.parent_id == nil %>
  <div class="card">
    <br>
    <strong>user:</strong> 
    <%= comment.user.name %>
    <br>
    <strong>Content:</strong>
    <%= comment.content %>
    <% if user_signed_in? && current_user.id == comment.user.id %>
      <%= link_to 'Edit', edit_comment_path(comment) %>
      <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <%  if comment.replies.any? %>
    <strong>Replies: </strong>
    <% comment.replies.each do |reply| %>
      <%= reply.content %><br>
    <% end %>
  <% end %>

    <%= form_with(model: @comment) do |form| %>
      <div class="field">
        <%= form.label :content, 'Reply' %>
        <br>
        <%= form.text_field :content %>
        <%= form.hidden_field :commentable_id,value: comment.commentable_id %>
        <%= form.hidden_field :commentable_type,value: comment.commentable_type %>
        <%= form.hidden_field :user_id,value: current_user.id %>
        <%= form.hidden_field :parent_id,value: comment.id %>
      </div>

      <div class="actions">
        <%= form.submit 'Add Reply' %>
      </div>
    <% end %>

  </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <%= form.hidden_field :user_id,value: current_user.id %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.text_field :end_time %>
  </div>
  <% Category.all.each do |c| %>
    <div>
      <%= check_box_tag :category_ids, c.id, event.categories.include?(c), :name => 'event[category_ids][]' %>
      <%= label_tag :category_ids, c.name -%>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Post',root_path,class:'navbar-brand btn btn-outline-primary' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active" id="navbar-item">
        <%= link_to 'Events',events_path,class:'nav-link btn btn-outline-secondary ' %>
      </li>
      <li class="nav-item" id="navbar-item">
        <%= link_to 'Images',images_path,class:'nav-link btn btn-outline-secondary' %>
      </li>
     
      <% if !user_signed_in? %>
        <li class="nav-item" id="navbar-item">
          <%= link_to 'Log In',new_user_session_path,class:'nav-link btn btn-outline-secondary' %>
        </li>
        <li class="nav-item" id="navbar-item">
          <%= link_to 'Sign Up',new_user_registration_path,class:'nav-link btn btn-outline-secondary' %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item" id="navbar-item">
          <%= link_to 'Log Out',destroy_user_session_path,:confirm => "Are you sure ?",:method => :delete,class:'nav-link btn btn-outline-secondary' %>
        </li>
        <li class="nav-item" id="navbar-item">
          <%= link_to 'My Profile',user_path(current_user),class:'nav-link btn btn-outline-secondary' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/events/_new_comment.html.erb
<%= form_with(model: @comment) do |form| %>
  <div class="field">
    <%= form.label :content, 'New Comment' %>
    <br>
    <%= form.text_field :content %>
    <%= form.hidden_field :commentable_id,value: obj.id %>
    <%= form.hidden_field :commentable_type,value: obj.class.name %>
    <%= form.hidden_field :user,value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <% if user_signed_in? && current_user.id == event.user.id  %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>
<% if user_signed_in? && current_user.id == @event.user.id %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>

<%= render 'comments',comments: @comments %>


<% if user_signed_in? && current_user.id == @event.user.id %>
  <%= render 'new_comment',obj: @event %>
<% end %>
<br>
<%= link_to 'Back', events_path %>