config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :tags
  end
  resources :comments do
  	collection do
  		get 'recent'
  	end
  end
  devise_for :users
  resources :users,only: [:show]
  resources :images
  resources :events
  resources :posts do
  	member do
  		get 'comments'
  	end
  end
  
  root 'posts#index'
  namespace :admin do
    #root 'dashboards#index'
    root "dashboards#posts"
    get "events/", to: "dashboards#events"
    get "images/", to: "dashboards#images"
    resources :users
    resources :categorizes
    resources :categories

  end
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments,as: :commentable
	has_many :categorizes,as: :categorizable
	has_many :categories,through: :categorizes
	accepts_nested_attributes_for :categorizes, allow_destroy: true, reject_if: proc {|attr| attr[:category_id].nil? }

	validates :title, length: {minimum: 3,maximum: 25},uniqueness: {message: "Must be unique."}
	validates_presence_of :title,:description,:slug

	before_validation :set_post_slug

	def to_param
		"#{id}-#{slug}"
	end

	private
	
	def set_post_slug
		self.slug = self.title.to_s.parameterize
	end
		
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,only: [:new,:update,:edit,:destroy]
  before_action :same_user, only: [ :edit, :update, :destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  
  
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user)
  end


  def comments
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
  
  def show
    @comment = Comment.new
    @comments = @post.comments.all
  end


  def new
    @post = Post.new
    @categorizes = Categorize.all
  end

  
  def edit
    @categorizes = Categorize.all
  end

  
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if params[:_destroy] == true
        @post.categorizes
      end
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description,:user_id,categorizes_attributes: [:id,:category_id,:categorizable_type,:categorizable_id,:_destroy])
    end

    def same_user
      unless current_user.id == @post.user.id
        redirect_to posts_path
      end
    end
    def record_not_found
      render plain: "404 Not Found", status: 404
    end
    
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <%= form.hidden_field :user_id,value: current_user.id %>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <h5>Category: </h5>
    <% Category.all.each.with_index do |c, index| %>
    <%= c.id%>
  <%#= form.fields_for "categorizes_attributes[#{index}]" do |ff| %>
  <%= form.fields_for "categorizes_attributes[#{index}]" do |ff| %>
      <div>
        <%#= ff.hidden_field :id, {value: post.categorizes.find_by(category_id: c.id).try(:id)} %>
        <%#= ff.hidden_field :_destroy,value: post.categories.include?(c)  %>
        <%#= ff.check_box :category_id, {checked: post.categories.include?(c)}, c.id,nil %>

        <%= ff.hidden_field :categorizable_type,value: post.class.name %>
        <%= ff.hidden_field :categorizable_id,value: post.id %>
        <%= ff.check_box :category_id, {checked: post.categories.include?(c)},c.id,nil %>
        <%= ff.hidden_field :_destroy,value: post.categories.none { |p| p==c }  %>


        <!-- <input type="hidden" value="<%= post.class.name %>" name="user[categorizes_attributes][<%= index %>][categorizable_type]">
        <input type="hidden" value="<%= post.id %>" name="user[categorizes_attributes][<%= index %>][categorizable_id]">

        <input type="checkbox" value="true" name="user[categorizes_attributes][<%= index %>][_destroy]">
        <input type="hidden" value="true" name="user[categorizes_attributes][<%= index %>][_destroy]"> -->
  
        <%= ff.label :category_id, c.name %>       
      </div>
    <% end %>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/comments.html.erb
<h5> All comments of <%= @post.title %> </h5>

<% @comments.each do |comment| %>
  <% if comment.parent_id == nil %>
  <div class="card">
    <br>
    <strong>user:</strong> 
    <%= comment.user.name %>
    <br>
    <strong>Content:</strong>
    <%= comment.content %>
    <% if user_signed_in? && current_user.id == comment.user.id %>
      <%= link_to 'Edit', edit_comment_path(comment) %>
      <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<%= search_form_for @q do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>
  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>
  <%= f.label :user_name_cont %>
  <%= f.search_field :user_name_cont %>
  <%= f.submit %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th><%= sort_link(@q,:title,'Title',default_order: :asc) %></th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? && current_user.id == post&.user&.id %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>
<% if user_signed_in? && current_user.id == @post&.user&.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>


<%= link_to 'comments',comments_post_path  %>
<%= render 'events/comments',comments: @comments %>

<% if user_signed_in? && current_user.id == @post.user.id %>
  <%= render 'events/new_comment',obj: @post %>
<% end %>
<br>
<%= link_to 'Back', posts_path %>