config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :tags
  end
  resources :comments do
  	collection do
  		get 'recent'
  	end
  end
  devise_for :users
  resources :users,only: [:show]
  resources :images
  resources :events
  resources :posts do
  	member do
  		get 'comments'
  	end
  end
  
  root 'posts#index'
  namespace :admin do
    #root 'dashboards#index'
    root "dashboards#posts"
    get "events/", to: "dashboards#events"
    get "images/", to: "dashboards#images"
    resources :users
    resources :categorizes
    resources :categories

  end
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::ApplicationController
	def index
	
	end
	def posts
		@posts = Post.all
	end
	def events
		@events = Event.all
	end
	def images
		@images = Image.all
	end

end

app/views/admin/dashboards/_sidebar.html.erb
<br><br>
<ul>
	<li>
		<%= link_to 'posts',admin_root_path %>
	</li>
	<li>
		<%= link_to 'events',admin_events_path %>
	</li>
	<li>
		<%= link_to 'images',admin_images_path %>
	</li>
	<li>
		<%= link_to 'categories',admin_categories_path %>
	</li>
	<li>
		<%= link_to 'users',admin_users_path %>
	</li>
</ul>

app/views/admin/dashboards/events.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <% if user_signed_in? && current_user.id == event.user.id  %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Event', new_event_path %>
<% end %>

app/views/admin/dashboards/images.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table class="table">
  <thead>
    <tr>
      <th>Caption</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.caption %></td>
        <td><%= image_tag image.caption_image %></td>
        <td><%= link_to 'Show', image %></td>
        <% if user_signed_in? && current_user.id == image&.user&.id %>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Image', new_image_path %>
<% end %>

app/views/admin/dashboards/posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? && current_user.id == post&.user&.id %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path %>
<% end %>