config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :tags
  end
  resources :comments do
  	collection do
  		get 'recent'
  	end
  end
  devise_for :users
  resources :users,only: [:show]
  resources :images
  resources :events
  resources :posts do
  	member do
  		get 'comments'
  	end
  end
  
  root 'posts#index'
  namespace :admin do
    #root 'dashboards#index'
    root "dashboards#posts"
    get "events/", to: "dashboards#events"
    get "images/", to: "dashboards#images"
    resources :users
    resources :categorizes
    resources :categories

  end
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :username, presence:true ,uniqueness: true
  has_many :posts
  has_many :events
  has_many :images
  has_many :comments
  belongs_to :role

  before_validation :set_role

  def set_role
    if self.role == nil
      self.role_id = 2
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name,:username,:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
  	@user = User.find(current_user.id)
  end

end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin,@user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit  %>
  </div>


<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>User Name</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td> 
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy',admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New User', new_admin_user_path %>
<% end %>

app/views/admin/users/new.html.erb
<h1>New Post</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>User Name:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_root_path %>